name: Build & Push to ghcr.io
on:
  push:
    branches: main

jobs:
  build-deploy:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          ecr: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64

      - name: Pin SearXNG version
        run: cd searxng && python3 searx/version.py freeze

      - name: Export version to environment
        run: |
          export RUNTIME_TAG=$(grep lambda/python Dockerfile | head -n1 | sed 's/^.*://' | sed 's/ .*$//')
          export SEARXNG_TAG=$(grep DOCKER_TAG searxng/searx/version_frozen.py | sed 's/^.*= "//' | sed 's/"$//')
          echo "DOCKER_TAG=v${SEARXNG_TAG}-${RUNTIME_TAG}" >> "$GITHUB_ENV"

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: |
            ghcr.io/${{ github.repository_owner }}/searxng-lambda:latest
            ghcr.io/${{ github.repository_owner }}/searxng-lambda:${{ env.DOCKER_TAG }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64
          push: true
