name: Build & Test Docker Image
on:
  pull_request:
  push:
    branches: main

jobs:
  draft-release:
    name: Draft next release
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    concurrency:
      group: release-draft
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
          fetch-depth: 0

      - name: Pin SearXNG version
        run: cd searxng && python3 searx/version.py freeze

      - name: Set version environment variables
        run: python3 scripts/version.py --bump patch >> "$GITHUB_ENV"

      - name: Generate release notes
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs");

            const { data } = await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ env.SEARXNG_LAMBDA_NEXT_VERSION }}",
              target_commitish: "${{ github.sha }}",
            });

            const { body: releaseNotes } = data;
            fs.writeFileSync(".github/RELEASE_NOTES.md", releaseNotes + "\n");


      - name: Build release body
        run: |
          cd .github
          cat - RELEASE_NOTES.md << "EOF" > RELEASE_BODY.md
          ## Summary

          | Component | Version |
          | :--- | :--- |
          | `${{ env.SEARXNG_LAMBDA_APP_IMAGE }}` | `${{ env.SEARXNG_LAMBDA_APP_VERSION }}` |
          | `${{ env.SEARXNG_LAMBDA_RUNTIME_IMAGE }}` | `${{ env.SEARXNG_LAMBDA_RUNTIME_TAG }}` |

          EOF

      - name: Create or update release draft
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/workflows/scripts/create-update-release-draft.js');
            const inputs = {
              nextVersion: "${{ env.SEARXNG_LAMBDA_NEXT_VERSION }}",
              sha: "${{ github.sha }}",
            };

            return await script({ github, context, inputs });

  build-test:
    name: Build & Test Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # v3.1.0
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0
        with:
          platforms: linux/arm64

      - name: Pin SearXNG version
        run: cd searxng && python3 searx/version.py freeze

      - name: Build Docker Image
        uses: docker/build-push-action@a254f8ca60a858f3136a2f1f23a60969f2c402dd # v6.4.0
        with:
          context: .
          tags: searxng-lambda:local-latest
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64
          push: false
          load: true

      - name: Setup Node JS
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          cache: npm
          cache-dependency-path: tests/package-lock.json

      - name: Start test containers
        run: cd tests && docker-compose up -d

      - name: Install NPM packages
        run: cd tests && npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: tests
          install: false

  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Lint with pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
