name: Build & Deploy to Lambda
on:
  push:
    branches: main

jobs:
  build-deploy:
    name: Build & Deploy Docker Image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     ecr: false

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.CI_AWS_ROLE }}
          role-duration-seconds: 900

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64

      - name: Pin SearXNG version
        run: cd searxng && python3 searx/version.py freeze

      - name: Export version to environment
        run: |
          export RUNTIME_TAG=$(grep lambda/python Dockerfile | head -n1 | sed 's/^.*://' | sed 's/ .*$//')
          export SEARXNG_TAG=$(grep DOCKER_TAG searxng/searx/version_frozen.py | sed 's/^.*= "//' | sed 's/"$//')
          echo "DOCKER_TAG=v${SEARXNG_TAG}-${RUNTIME_TAG}" >> "$GITHUB_ENV"

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: |
            ${{ secrets.CI_CONTAINER_REPO }}:latest
            ${{ secrets.CI_CONTAINER_REPO }}:${{ env.DOCKER_TAG }}
          # ghcr.io/${{ github.repository_owner }}/searxng-lambda:latest
          # ghcr.io/${{ github.repository_owner }}/searxng-lambda:${{ env.DOCKER_TAG }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true

      - name: Upload static assets to S3
        run: |
          cd searxng/searx
          aws s3 sync ./static ${{ secrets.CI_STATIC_BUCKET }}/static --delete

      - name: Reload Lambdas
        run: |
          aws lambda update-function-code \
            --function-name "${{ secrets.CI_LAMBDA_NAME }}" \
            --image-uri "${{ secrets.CI_CONTAINER_REPO }}:${{ env.DOCKER_TAG }}" > /dev/null
          aws lambda wait function-active --function-name "${{ secrets.CI_LAMBDA_NAME }}" > /dev/null
