name: Build & Push to ghcr.io
on:
  push:
    branches: main

jobs:
  build-deploy:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          ecr: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64

      - name: Pin SearXNG version
        run: cd searxng && python3 searx/version.py freeze

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: searxng-lambda:local-latest
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64
          push: false
          load: true

      - name: Export version to environment
        run: |
          echo "DOCKER_TAG=$(./scripts/version.py)" >> "$GITHUB_ENV"
          if ! git diff --quiet HEAD^ HEAD -- version.json ; then
            echo "VERSION_CHANGED=1" >> "$GITHUB_ENV"
          fi

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: tests/package-lock.json

      - name: Start test containers
        run: cd tests && docker-compose up -d

      - name: Install NPM packages
        run: cd tests && npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: tests
          install: false

      - name: Push Docker Image
        uses: docker/build-push-action@v4
        if: ${{ env.VERSION_CHANGED }}
        with:
          context: .
          tags: |
            ghcr.io/${{ github.repository_owner }}/searxng-lambda:latest
            ghcr.io/${{ github.repository_owner }}/searxng-lambda:${{ env.DOCKER_TAG }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64
          push: true
