name: PR Check
on:
  pull_request:

concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  pr-check:
    name: Build & Test Docker Image
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64

      - name: Pin SearXNG version
        run: cd searxng && python3 searx/version.py freeze

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: |
            searxng-lambda:local-latest
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64
          push: false
          load: true

      - name: Bump and export version to environment
        run: |
          echo "DOCKER_TAG=$(./scripts/version.py)" >> "$GITHUB_ENV"
          if ! git diff --quiet version.json ; then
            echo "VERSION_CHANGED=1" >> "$GITHUB_ENV"
            git diff version.json > version_diff
          fi

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: tests/package-lock.json

      - name: Start test containers
        run: cd tests && docker-compose up -d

      - name: Install NPM packages
        run: cd tests && npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: tests
          install: false

      - name: Hide old comments
        uses: kanga333/comment-hider@master
        if: ${{ env.VERSION_CHANGED }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a PR comment
        uses: actions/github-script@v6
        if: ${{ env.VERSION_CHANGED }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const versionDiff = fs.readFileSync('./version_diff', 'utf8');

            let body = '## ⚠️ Image tag changed\n';
            body += 'The Docker image will be tagged and pushed with the following contents when this PR is merged:\n\n';
            body += '```diff\n';  
            body += versionDiff;
            body += '```';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })

      - name: Commit new version.json to PR
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ env.VERSION_CHANGED }}
        with:
          commit_message: Bump `version.json` for ${{ env.DOCKER_TAG }}
          file_pattern: version.json
          commit_user_name: Automated FluxCI Bot
          commit_user_email: automated@flux.ci
