name: Release Docker Image
on:
  release:
    types: [published]

jobs:
  build-release:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    concurrency:
      group: release
    permissions:
      packages: write
      contents: write
    env:
      SEARXNG_LAMBDA_THIS_RELEASE_TAG: ${{ github.event.release.tag_name }}-arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v2
        with:
          platforms: linux/arm64

      - name: Pin SearXNG version
        run: cd searxng && python3 searx/version.py freeze

      - name: Build Docker Image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
        with:
          context: .
          tags: searxng-lambda:local-latest
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64
          push: false
          load: true

      - name: Setup Node JS
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          cache: npm
          cache-dependency-path: tests/package-lock.json

      - name: Start test containers
        run: cd tests && docker-compose up -d

      - name: Install NPM packages
        run: cd tests && npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: tests
          install: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          ecr: false

      - name: Push Docker Images
        run: |
          docker tag searxng-lambda:local-latest ghcr.io/${{ github.repository_owner }}/searxng-lambda:latest
          docker tag searxng-lambda:local-latest ghcr.io/${{ github.repository_owner }}/searxng-lambda:${{ env.SEARXNG_LAMBDA_THIS_RELEASE_TAG }}
          docker push ghcr.io/${{ github.repository_owner }}/searxng-lambda:latest
          docker push ghcr.io/${{ github.repository_owner }}/searxng-lambda:${{ env.SEARXNG_LAMBDA_THIS_RELEASE_TAG }}
