name: Release Docker Image
on:
  release:
    types: [published]

jobs:
  build-release:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    concurrency:
      group: release
    permissions:
      packages: write
      contents: write
    env:
      SEARXNG_LAMBDA_THIS_RELEASE_TAG: ${{ github.event.release.tag_name }}-arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3
        with:
          platforms: linux/arm64

      - name: Pin SearXNG version
        run: cd searxng && python3 searx/version.py freeze

      - name: Build Docker Image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
          context: .
          tags: searxng-lambda:local-latest
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64
          push: false
          load: true

      - name: Setup Node JS
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          cache: npm
          cache-dependency-path: tests/package-lock.json

      - name: Start test containers
        run: cd tests && docker-compose up -d

      - name: Install NPM packages
        run: cd tests && npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: tests
          install: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          ecr: false

      - name: Push Docker Images
        run: |
          docker tag searxng-lambda:local-latest ghcr.io/${{ github.repository_owner }}/searxng-lambda:latest
          docker tag searxng-lambda:local-latest ghcr.io/${{ github.repository_owner }}/searxng-lambda:${{ env.SEARXNG_LAMBDA_THIS_RELEASE_TAG }}
          docker push ghcr.io/${{ github.repository_owner }}/searxng-lambda:latest
          docker push ghcr.io/${{ github.repository_owner }}/searxng-lambda:${{ env.SEARXNG_LAMBDA_THIS_RELEASE_TAG }}
